-- 코드를 입력하세요
SET @h = 0;

SELECT H.HOUR, IFNULL(OUTS.COUNT, 0) FROM
(SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS GROUP BY HOUR) OUTS RIGHT JOIN
(SELECT @h HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT
UNION ALL
SELECT @h := @h + 1 HOUR, 0 COUNT) H
ON H.HOUR = OUTS.HOUR
ORDER BY HOUR